Name:           ros-lunar-gazebo-ros-control
Version:        2.7.1
Release:        0%{?dist}
Summary:        ROS gazebo_ros_control package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/gazebo_ros_control
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-angles
Requires:       ros-lunar-control-toolbox
Requires:       ros-lunar-controller-manager
Requires:       ros-lunar-gazebo-ros
Requires:       ros-lunar-hardware-interface
Requires:       ros-lunar-joint-limits-interface
Requires:       ros-lunar-pluginlib
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-std-msgs
Requires:       ros-lunar-transmission-interface
Requires:       ros-lunar-urdf
BuildRequires:  ros-lunar-angles
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-control-toolbox
BuildRequires:  ros-lunar-controller-manager
BuildRequires:  ros-lunar-gazebo-dev
BuildRequires:  ros-lunar-hardware-interface
BuildRequires:  ros-lunar-joint-limits-interface
BuildRequires:  ros-lunar-pluginlib
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-std-msgs
BuildRequires:  ros-lunar-transmission-interface
BuildRequires:  ros-lunar-urdf

%description
gazebo_ros_control

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Fri Apr 28 2017 Jose Luis Rivero <jrivero@osrfoundation.org> - 2.7.1-0
- Autogenerated by Bloom

