Name:           ros-lunar-gazebo-ros
Version:        2.7.1
Release:        0%{?dist}
Summary:        ROS gazebo_ros package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://gazebosim.org/tutorials?cat=connect_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-dynamic-reconfigure
Requires:       ros-lunar-gazebo-dev
Requires:       ros-lunar-gazebo-msgs
Requires:       ros-lunar-geometry-msgs
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-rosgraph-msgs
Requires:       ros-lunar-roslib
Requires:       ros-lunar-std-msgs
Requires:       ros-lunar-std-srvs
Requires:       ros-lunar-tf
Requires:       tinyxml-devel
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-cmake-modules
BuildRequires:  ros-lunar-dynamic-reconfigure
BuildRequires:  ros-lunar-gazebo-dev
BuildRequires:  ros-lunar-gazebo-msgs
BuildRequires:  ros-lunar-geometry-msgs
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-rosgraph-msgs
BuildRequires:  ros-lunar-roslib
BuildRequires:  ros-lunar-std-msgs
BuildRequires:  ros-lunar-std-srvs
BuildRequires:  ros-lunar-tf
BuildRequires:  tinyxml-devel

%description
Provides ROS plugins that offer message and service publishers for interfacing
with Gazebo through ROS. Formally simulator_gazebo/gazebo

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Fri Apr 28 2017 Jose Luis Rivero <jrivero@osrfoundation.org> - 2.7.1-0
- Autogenerated by Bloom

